### ISSUE TITLE
Cannot get SQL for: Subtract

### ISSUE THREAD

**Issue by ASheikhi82** [oysteinkrog/SQLite.Net-PCL#110] opened 2015-01-15 03:58 UTC
Hi,

I'm using SQLite For Windows Phone 8.1 V3.8.7.4. When I try to select some records from the database, I get the following exception:

Cannot get SQL for: Subtract

What should I do?

**Comment by oysteinkrog** [comment] 2015-02-01 14:13
Provide more information:)

**Comment by Shiney** [comment] 2015-04-06 21:27
I think the issue is that the TableQuery code does not translate the "-" operator in a lambda expression to the equivalent SQL.

**Comment by oysteinkrog** [comment] 2015-04-11 11:41
I am closing this, please reopen if the merged fix in #164 does not actually work.

**Closed by oysteinkrog** 2015-04-11 11:41 UTC
