### ISSUE TITLE
Installing WinRT verison on VisualStudio 2013 Update 4

### ISSUE THREAD

**Issue by interjaz** [oysteinkrog/SQLite.Net-PCL#116] opened 2015-01-27 14:44 UTC
Hi, it seems that there is an issue with the Package *SQLite.WinRT.redist* that *SQLite.Net-PCL* is depending on. The *SQLite.WinRT.redist* is no longer installing on visual studio. The Install.ps1 file failes with *Unable to load type information for the VS Extension Manage* (64 line - https://github.com/timheuer/SQLite-WinRT-redist/blob/master/nuget/scripts/Install.ps1). 

Also the *SQLite.WinRT.redist* does not seem to be developed anymore and is based on old vs extension.

**Comment by rmaclean** [comment] 2015-01-28 11:50
Same issue - here is the output from the package manager console

```
Install-Package : Unable to load type information for the VS Extension Manager
At line:1 char:1
+ Install-Package SQLite.Net.Platform.WinRT
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], RuntimeException
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PowerShell.Commands.InstallPackageCommand
```

**Comment by rmaclean** [comment] 2015-01-28 12:42
Created a pull request to resolve this: https://github.com/oysteinkrog/SQLite.Net-PCL/pull/117

**Comment by rmaclean** [comment] 2015-01-28 12:52
And for a work around until an official solution, I created my own nuget package (actually downloaded the nupkg file, unzippped it, editted the nuspec file and uploaded it) so it is up at: https://www.nuget.org/packages/SQLite.Net.Platform.WinRT.StopGap/2.5.0

**Comment by oysteinkrog** [comment] 2015-02-01 14:30
I've merged your PR and published new nugets, please verify that the problem is fixed:)

**Comment by rmaclean** [comment] 2015-02-02 06:22
Can confirm it is fixed :)

**Comment by oysteinkrog** [comment] 2015-02-02 09:49
Awesome, thank you:)

**Closed by oysteinkrog** 2015-02-02 09:49 UTC
